---
- name: Ensure S3 bucket exists
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ s3_bucket_name }}"
      register: s3_bucket_info

    - name: Create S3 bucket if it doesn't exist
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: present
        public_access:
          block_public_acls: true
          ignore_public_acls: true
      when: s3_bucket_info.buckets is not defined
