---
- name: Deploy service using terraform collection.
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  collections:
    - cloud.terraform
    
  tasks:
    - name: Apply terraform 
      cloud.terraform.terraform:
        project_path: 'terraform/'
        state: present
        backend_config:
          region: "{{ region }}"
          bucket: "{{ s3_bucket_name }}"
          key: "terraform.tfstate"
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output
